### PR TITLE
Added Menu Links as Nav Bar

### PR DESCRIPTION
**Pull request by chttrjeankr**
## Changes made:
* NavBar introduced
* New colour codes used in accordance to https://shubhamkumar.live/

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Documentation update (Documentation content changed).
- [ ] Other (please describe).

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project.
- [ ] I have made corresponding changes to the documentation.

## Screenshots

image

### CODE REVIEW

**Comment by chttrjeankr** [comment]
New screenshot:
image

**Comment by imskr** [comment]
5:30  error  'menuLinks' is missing in props validation      react/prop-types
  33:24  error  'menuLinks.map' is missing in props validation  react/prop-types

**Comment by imskr** [comment]
Before commit always run `yarn lint`

**Comment by chttrjeankr** [comment]
Thanks for helping me out there @imskr. I'm a complete beginner in ReactJS and I thought it's good to go since the website looked like it should be. The React typechecking part wasn't known to me.

Ran `yarn lint` on my new changes and created a commit. Hope this solves it.

**Comment by chttrjeankr** [comment]
```
$ snyk protect
Failed to fetch patch from https://snyk-patches.s3.amazonaws.com/npm/lodash/20200430/lodash_0_0_20200430_6baae67d501e4c45021280876d42efe351e77551.patch to /tmp/e2e07bf4-c0aa-43fa-a97f-3c33ba618a0c.SNYK-JS-LODASH-567746.snyk-patch
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command "yarn --frozen-lockfile" failed and exited with 2 during .
```
I'm not sure if this new error is due to my changes. :question:

**Comment by imskr** [comment]
@chttrjeankr Its issue with synk. Let me test it.

**Comment by imskr** [comment]
@chttrjeankr I fixed some error in synk. Can you please send fresh PR including changes? Make sure to fetch from master before making changes. Also delete your `node_modules` and run `yarn install` again

**Comment by chttrjeankr** [comment]
A simple `git rebase` would have been an easy way out.

**Comment by imskr** [comment]
@chttrjeankr Yes, but I had changed synk and yarn.lock and may have resulted in merge conflict.

**Pull request closed without merging**
